AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy Express.js App on EC2 with IAM Role and S3 Access

Parameters:
  ProjectName:
    Type: String
    Default: ExpressApp
    Description: Name of the project/application

  Environment:
    Type: String
    Default: dev
    Description: Deployment environment

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair

  BucketName:
    Type: String
    Description: S3 Bucket name where the application zip is stored
    Default: test-ec2-s3bucket

  ZipFile:
    Type: String
    Description: Name of the application zip file in the S3 bucket
    Default: app.zip

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
      - t3.small

Resources:
  ###############################################
  # IAM ROLE FOR EC2
  ###############################################
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-${ProjectName}-EC2-Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy

      Policies:
        - PolicyName: S3ReadAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${BucketName}"
                  - !Sub "arn:aws:s3:::${BucketName}/*"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-${ProjectName}-Role"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "${Environment}-${ProjectName}-InstanceProfile"
      Roles:
        - !Ref EC2Role

  ###############################################
  # SECURITY GROUP
  ###############################################
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${Environment}-${ProjectName}-sg"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH Access
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
          Description: Express App Port
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP Access
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-${ProjectName}-sg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  ###############################################
  # EC2 INSTANCE
  ###############################################
  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn: EC2InstanceProfile
    Properties:
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref EC2InstanceProfile
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      ImageId: ami-0cae6d6fe6048ca2c
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-${ProjectName}-instance"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            set -e

            # Install CodeDeploy Agent ONLY
            dnf update -y
            dnf install -y ruby wget

            cd /home/ec2-user
            wget https://aws-codedeploy-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/latest/install
            chmod +x install
            ./install auto

            systemctl enable codedeploy-agent
            systemctl start codedeploy-agent



###############################################
# OUTPUTS
###############################################
Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
  
  PublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
  
  AppURL:
    Description: URL to access the Express application
    Value: !Sub "http://${EC2Instance.PublicIp}:3000"
  
  SSHCommand:
    Description: SSH command to connect
    Value: !Sub "ssh -i ${KeyPairName}.pem ec2-user@${EC2Instance.PublicIp}"
  
  RoleName:
    Description: IAM Role Name
    Value: !Ref EC2Role
  
  InstanceProfileName:
    Description: IAM Instance Profile Name
    Value: !Ref EC2InstanceProfile